version: "3.8"

services:
  mynginx:
    build: .
    container_name: mynginx
    ports:
      - "8080:8080"
    volumes:
      - ./www:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
